// auth
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const ALL_USER_LOADED = 'ALL_USER_LOADED';
export const ALL_USER_LOADING = 'ALL_USER_LOADING';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION'
export const AUTH_ERROR = 'AUTH_ERROR'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOG_OUT = 'LOG_OUT'
export const GET_ERROR = 'GET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const DASHBOARD_USER = 'DASHBOARD_USER'
export const DELETE_USER = 'DELETE_USER'
export const USER_UPGRADED = 'USER_UPGRADED'

// menu
export const MENU_LOADING = 'MENU_LOADING'
export const MENU_LOADED = 'MENU_LOADED'
export const POST_MENU = 'POST_MENU'
export const FETCH_SINGLE_MENU = 'FETCH_SINGLE_MENU'
export const DELETE_MENU = 'DELETE_MENU'
export const UPDATE_MENU = 'UPDATE_MENU'
export const CLEAR_SINGLE_MENU_STATE = 'CLEAR_SINGLE_MENU_STATE'

// order
export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDER_LOADED = 'ORDER_LOADED'
export const GET_SINGLE_ORDER = 'GET_SINGLE_ORDER'
export const POST_ORDER = 'POST_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const UPDATE_ORDER_QUANTITY = 'UPDATE_ORDER_QUANTITY'
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS'

export const FETCH_USER_HISTORY = 'FETCH_USER_HISTORY'
export const UPDATE_USER_ORDER_PAYMENT = 'UPDATE_USER_ORDER_PAYMENT'
export const USER_HISTORY_LOADING = 'USER_HISTORY_LOADING';

export const TOTAL = 'TOTAL'